ShopBridge/Models/ItemRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShopBridge.Models
{
    public class ItemRepository
    {
        // 1) fetch based on flag or not
        public ICollection<Item> GetItems(bool IsInventory)
        {
            List<Item> items = new List<Item>();
            using (ShopBridgeEntities db = new ShopBridgeEntities())
            {
                if (IsInventory)
                {
                    // Inventory bucket
                    items = db.Items.Where(x => x.IsInventory == true).ToList();
                }
                else
                {
                    // Component Bucket
                    items = db.Items.Where(x => x.IsInventory == false).ToList();
                }
            }
            return items;
        }

        // Get Item By ID
        public Item GetItemByID(int Id)
        {
            Item item = new Item();
            using (ShopBridgeEntities db = new ShopBridgeEntities())
            {
                if (Id !=0)
                {
                   
                    item = db.Items.Where(x => x.ItemId == Id).ToList().FirstOrDefault();
                }
                else
                {
                    return null;
                }
            }
            return item;
        }

        // 2) Add item to the inventory
        public bool AddItem(int Id)
        {
            if (Id != 0)
            {
                using (ShopBridgeEntities db = new ShopBridgeEntities())
                {
                    Item result = db.Items.Where(x => x.ItemId == Id).ToList().FirstOrDefault();
                    result.IsInventory = true;
                    db.SaveChanges();
                    return true;
                }
            }
            else
                return false;
        }

        //3) Remove Item frpom the inventory
        public bool RemoveItem(int Id)
        {
            if (Id != 0)
            {
                using (ShopBridgeEntities db = new ShopBridgeEntities())
                {
                    Item result = db.Items.Where(x => x.ItemId == Id).ToList().FirstOrDefault();
                    result.IsInventory = false;
                    db.SaveChanges();
                    return true;
                }
            }
            else
                return false;
        }


    }
}

ShopBridge/Controllers/APIController.cs
using ShopBridge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Routing;

namespace ShopBridge.Controllers
{
    [RoutePrefix("MyAPI")]
    public class APIController : ApiController
    {       
        ItemRepository repository = new ItemRepository();

        // 1) Get Items for both the buckets
        [Route("GetItemsList")]
        public HttpResponseMessage GetItemsList(bool IsInventory)
        {
            
            List<Item> items = repository.GetItems(IsInventory).ToList();

            return Request.CreateResponse(HttpStatusCode.OK, items);
        }



        //3) Add Item to inventory
        [Route("AddInventory")]
        [HttpGet]
        public HttpResponseMessage AddInventory(int Id)
        {
            if(Id != 0)
            {
                bool val = repository.AddItem(Id);
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
                return Request.CreateResponse(HttpStatusCode.NotFound);
        }

        // 4) Remove Item from inventory: RemoveItem
        [Route("RemoveInventory")]
        [HttpGet]
        public HttpResponseMessage RemoveInventory(int Id)
        {
            if (Id != 0)
            {
                bool val = repository.RemoveItem(Id);
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
                return Request.CreateResponse(HttpStatusCode.NotFound);
        }
    }
}

ShopBridge/Controllers/ItemsController.cs
using ShopBridge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopBridge.Controllers
{
    public class ItemsController : Controller
    {
        // GET: HomePage
        public ActionResult HomePage()
        {
            return View();
        }

        // Get Details of Items
        public ActionResult GetDetails(int Id)
        {
            ItemRepository itemRepository = new ItemRepository();
            Item result = itemRepository.GetItemByID(Id);
            if (result == null)
            {
                ViewBag.result = "Item details not found";
            }
            return View(result);
        }
    }
}

ShopBridge/Views/Items/GetDetails.cshtml
@model ShopBridge.Item

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetDetails</title>
</head>
<body>
    <div>
        <h4>Item</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ItemName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ItemName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            @*<dt>
                @Html.DisplayNameFor(model => model.IsInventory)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsInventory)
            </dd>*@
    
        </dl>
    </div>
</body>
@Html.ActionLink("Back to Main Page", "HomePage", "Items")
</html>

ShopBridge/Views/Items/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
}

<h2>HomePage</h2>

<h3>Components List</h3>
<table id="Component">
    <thead>
        
    </thead>
    <tbody id="ComponentBody">
        <tr>
            @*// Add the items in component from the JQuery class*@
        </tr>
    </tbody>
</table>

<h3>Inventory List</h3>
<table id="Inventory">
    <thead>
        
    </thead>
    <tbody id="InventoryBody">
        
            @*// Add the items in Inventory from the JQuery class*@
        
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        debugger;
        GetComponent();
        GetInventory();
    });

    function RefreshLists() {
        GetComponent();
        GetInventory();
    }
    function GetComponent() {
        $.ajax({
            cache: false,
            type: "GET",
            url: 'http://localhost:49934/MyAPI/GetItemsList',
            //dataType: 'json',
            data: {IsInventory: "false"},
            success: function (result) {
                var html = '';
                $.each(result, function (key, item) {
                    html += '<tr>';
                    html += '<td> Name: </td>';
                    html += '<td>' + item.ItemName + '</td>';
                    html += '<td> , Description: </td>';
                    html += '<td>' + item.Description + '</td>';
                    html += '<td> , Price: </td>';
                    html += '<td>' + item.Price + '</td>';
                    html += '<td><a href="GetDetails/' + item.ItemId + '"> Details | </a >'
                    html += '<td><a onclick="AddInventory(' + item.ItemId + ');"> Add </a></td > ';
                    html += '</tr>';
                });
                $('#ComponentBody').html(html);                
            },
            error: function () {

            }
        });
    }


    function GetInventory() {
        $.ajax({
            cache: false,
            type: "GET",
            url: 'http://localhost:49934/MyAPI/GetItemsList',
            //dataType: 'json',
            data: { IsInventory: "true" },
            success: function (result) {
                var html = '';
                $.each(result, function (key, item) {
                    html += '<tr>';
                    html += '<td> Name: </td>';
                    html += '<td>' + item.ItemName + '</td>';
                    html += '<td> , Description: </td>';
                    html += '<td>' + item.Description + '</td>';
                    html += '<td> , Price: </td>';
                    html += '<td>' + item.Price + '</td>';
                    html += '<td><a href="GetDetails/' + item.ItemId + '"> Details | </a >'
                    html += '<td><a onclick="RemoveInventory(' + item.ItemId + ');"> Remove </a></td > ';
                    html += '</tr>';
                });
                $('#InventoryBody').html(html);

            },
            error: function () {

            }
        });
    }

    function AddInventory(ItemId) {
        debugger;
        $.ajax({
            cache: false,
            type: "GET",
            url: 'http://localhost:49934/MyAPI/AddInventory',
            //dataType: 'json',
            data: { Id: ItemId },
            success: function (result) {
                RefreshLists();

            },
            error: function () {

            }
        });
    }

    function RemoveInventory(ItemId) {
        debugger;
        $.ajax({
            cache: false,
            type: "GET",
            url: 'http://localhost:49934/MyAPI/RemoveInventory',
            //dataType: 'json',
            data: { Id: ItemId },
            success: function (result) {
                RefreshLists();

            },
            error: function () {

            }
        });
    }
</script>

ShopBridge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>